# Análise dos materiais ricos - 2017

O intuito desta análise é entender, a partir do modelo e tipo de material, qual a sua performance em relação à quantidade de download para melhor planejamento de quantidade de materiais necessárias para alcance das métricas do ano de 2018.

A conclusão ideal é que chegamos em:
- Materiais do tipo planilha geram **x** downloads e **y%** vem de forma orgânica e **z%**vem de forma paga.
- Para chegar em **x** leads, é necessário **y** materiais do tipo **z**

In [69]:
#!pip install tqdm

Collecting tqdm
  Downloading tqdm-4.19.5-py2.py3-none-any.whl (51kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.19.5

In [70]:
import requests
import urllib3
import numpy as np
import pandas as pd
import json
import datetime
import collections
from tqdm import tqdm

In [67]:
materiais = pd.read_csv('data/material_v2-2.csv', sep=';')

In [68]:
materiais.head()

,month+year first conv date,day first conv date,Week first conv date,month first conv date,year first conv date,first conversion date,origem,email domain analysis,Conversões,Eventos (Últimos 100)
0,01/01/2017,1,1,1,2017,01/01/2017,Desconhecido,0,3,IntegracaoExact / checklist-de-atendimento-ao-...
1,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Dados Pessoais / Criação de...
2,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Sucesso / Criação de Conta ...
3,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Sucesso / Criação de Conta ...
4,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,1,4,Criação de Conta - Sucesso / Criação de Conta ...

Afim de padronizar o nome das colunas, iremos renomeá-las para melhor operação da análise

In [15]:
materiais = materiais.rename(index=str, columns={'month+year first conv date':'month_year_conv', 'day first conv date':'day_conv',\
                                     'Week first conv date': 'week_conv', 'month first conv date': 'month_conv', \
                                     'year first conv date': 'year_conv', 'first conversion date': 'date_conv', \
                                     'origem': 'source', 'email domain analysis': 'domain', 'Conversões': 'conversions', \
                                     'Eventos (Últimos 100)': 'events'})

In [16]:
materiais.head()

,month_year_conv,day_conv,week_conv,month_conv,year_conv,date_conv,source,domain,conversions,events
0,01/01/2017,1,1,1,2017,01/01/2017,Desconhecido,0,3,IntegracaoExact / checklist-de-atendimento-ao-...
1,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Dados Pessoais / Criação de...
2,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Sucesso / Criação de Conta ...
3,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Sucesso / Criação de Conta ...
4,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,1,4,Criação de Conta - Sucesso / Criação de Conta ...

Agora, iremos quebrar a coluna 'events' para ter todos os eventos quebrados de forma unificada.

In [23]:
split_materiais = materiais['events'].str.split(' / ', expand=True)

In [24]:
materiais_final = materiais.join(split_materiais)

In [25]:
materiais_final.head()

,month_year_conv,day_conv,week_conv,month_conv,year_conv,date_conv,source,domain,conversions,events,...,90,91,92,93,94,95,96,97,98,99
0,01/01/2017,1,1,1,2017,01/01/2017,Desconhecido,0,3,IntegracaoExact / checklist-de-atendimento-ao-...,...,None,None,None,None,None,None,None,None,None,None
1,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Dados Pessoais / Criação de...,...,None,None,None,None,None,None,None,None,None,None
2,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Sucesso / Criação de Conta ...,...,None,None,None,None,None,None,None,None,None,None
3,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,0,4,Criação de Conta - Sucesso / Criação de Conta ...,...,None,None,None,None,None,None,None,None,None,None
4,01/01/2017,2,1,1,2017,02/01/2017,Desconhecido,1,4,Criação de Conta - Sucesso / Criação de Conta ...,...,None,None,None,None,None,None,None,None,None,None

In [32]:
materiais_final.drop(labels=['events'], inplace=True, axis=1)

In [33]:
materiais_final.columns

Index(['month_year_conv',        'day_conv',       'week_conv',
            'month_conv',       'year_conv',       'date_conv',
                'source',          'domain',     'conversions',
                       0,
       ...
                      90,                91,                92,
                      93,                94,                95,
                      96,                97,                98,
                      99],
      dtype='object', length=109)

In [43]:
materiais_final[0]

0                                   IntegracaoExact
1                 Criação de Conta - Dados Pessoais
2                        Criação de Conta - Sucesso
3                        Criação de Conta - Sucesso
4                        Criação de Conta - Sucesso
5                Criação de Conta - Dados de Acesso
6                        Criação de Conta - Sucesso
7                        Criação de Conta - Sucesso
8                Criação de Conta - Dados de Acesso
9                                   IntegracaoExact
10                Criação de Conta - Dados Pessoais
11                       Criação de Conta - Sucesso
12                       Criação de Conta - Sucesso
13                Criação de Conta - Dados Pessoais
14                       Criação de Conta - Sucesso
15                       Criação de Conta - Sucesso
16                       Criação de Conta - Sucesso
17                                  IntegracaoExact
18           blog-exit-intent-lightbox-optinmonster
19               Criação de Conta - Dados de Acesso
20                       Criação de Conta - Sucesso
21                       Criação de Conta - Sucesso
22                Criação de Conta - Dados Pessoais
23              Criação de Conta - Dados da Empresa
24                       Criação de Conta - Sucesso
25                       Criação de Conta - Sucesso
26                  site-institucional-page-contato
27                Criação de Conta - Dados Pessoais
28                                  site-newsletter
29                    importacao-users-julho-tag-v2
                            ...
17619    site-materiais-ebook-qualidade-atendimento
17620                       kit-planejamento-treasy
17621                       kit-planejamento-treasy
17622             lp-ad-sistema-atendimento-cliente
17623              planilha-chamados-de-atendimento
17624                               IntegracaoExact
17625                               IntegracaoExact
17626            planilha-de-atendimento-ao-cliente
17627                       kit-planejamento-treasy
17628                       kit-planejamento-treasy
17629                              lp-cxtrends-2017
17630                       kit-planejamento-treasy
17631                       kit-planejamento-treasy
17632            planilha-de-atendimento-ao-cliente
17633                              lp-cxtrends-2017
17634                       kit-planejamento-treasy
17635                               IntegracaoExact
17636              planilha-chamados-de-atendimento
17637              planilha-chamados-de-atendimento
17638                               IntegracaoExact
17639                       kit-planejamento-treasy
17640                       kit-planejamento-treasy
17641                               IntegracaoExact
17642                               IntegracaoExact
17643                       kit-planejamento-treasy
17644                       kit-planejamento-treasy
17645                       kit-planejamento-treasy
17646                       kit-planejamento-treasy
17647                               IntegracaoExact
17648                              lp-cxtrends-2017
Name: 0, Length: 17649, dtype: object

In [ ]:
events = pd.DataFrame([])

for x in tqdm(range(0,100)):
    events = events.append(materiais_final[x], ignore_index=True)

  4%|▍         | 4/100 [00:04<01:37,  1.01s/it]

In [76]:
events2 = events.dropna(axis=1, how='any')

In [77]:
events

,0,1,10,100,1000,10000,10001,10002,10003,10004,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,IntegracaoExact,Criação de Conta - Dados Pessoais,Criação de Conta - Dados Pessoais,Criação de Conta - Sucesso,IntegracaoExact,checklist-de-atendimento-ao-cliente,planilha-de-atendimento-ao-cliente,planilha-de-atendimento-ao-cliente,planilha-de-atendimento-ao-cliente,jornada-do-cliente-agendor,...,IntegracaoExact,IntegracaoExact,IntegracaoExact,jornada-do-cliente-agendor,lp-kit-todas-as-planilhas,planilha-de-atendimento-ao-cliente,planilha-de-atendimento-ao-cliente,IntegracaoExact,lp-manual-rapido-nps,IntegracaoExact